services:
  cache:
    image: redis
  
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5431:5432"

  migrations:
    build: .
    volumes:
      - .:/backend
    command: sh -c "sleep 5s && alembic upgrade head"
    env_file:
      - .env
    depends_on:
      - db

  app:
    build: .
    volumes:
      - .:/backend
      - static_volume:/static
      - uploads_volume:/uploads
    command: [ "uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000" ]
    env_file:
      - .env
    depends_on:
      - migrations
      - db
      - cache

volumes:
  static_volume:
  uploads_volume:
  
networks:
  main-network: