"""empty message

Revision ID: 4f2e7e4a1d8a
Revises: 5d4a3c9ecda3
Create Date: 2025-01-12 12:40:55.962704

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4f2e7e4a1d8a'
down_revision: Union[str, None] = '5d4a3c9ecda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'status')
    # ### end Alembic commands ###
