name: CI/CD Tests Pipeline

on:
  push:
    branches:
      - develop  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          docker compose --version

      - name: Set environment variables from Secrets
        run: |
          echo "REDIS_HOST=cache" >> .env
          echo "PRODUCTION_MODE=1" >> .env
          echo "SECRET_KEY=secret" >> .env
          echo "POSTGRES_USER=cart_user" >> .env
          echo "POSTGRES_PASSWORD=cart_password" >> .env
          echo "POSTGRES_DB=cart_db" >> .env
          echo "POSTGRES_HOST=db" >> .env
          echo "POSTGRES_PORT=5432" >> .env

      - name: Build and start containers
        run: |
          docker compose -f docker-compose-test.yaml up --build  -d

      - name: Run tests
        run: |
          docker compose -f docker-compose-test.yaml exec app poetry run pytest

      - name: Stop containers
        run: |
          docker compose -f docker-compose-test.yaml down